version: "3.7"

x-static-content-volume:
  &static-content-volume
  type: bind
  source: ./web/frontend
  target: /usr/src/app/frontend

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8080:8080"
    volumes:
      - *static-content-volume
    networks:
      - backnet
      - frontnet
    env_file:
      - .env
    command: /usr/local/bin/gunicorn main:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - *static-content-volume
    networks:
      - frontnet

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - backnet
    env_file:
      - .env

volumes:
  db-data:
  web-data:

networks:
  backnet:
  frontnet: